*** Variables ***
${Cookies}              //a[@class="call"]
${Maincontent}          //div[@class="mainContent"]
${Frame}                //iframe[contains(@id, "pop-frame")]
${Mobile}               //a[@data-di-id="di-id-7c56fcc8-3103e56f"]    #//span[@class=""]    #//a[@href="https://www.bt.com/mobile"]   //a[conatins(@data-di-id="di-id")]
${Mobile_Phones}        //a[@data-di-id="di-id-1672f262-8d36f8c2"]
${Banner_Class}         //div[@class="flexpay-card_card_wrapper__Antym"]    #//div[@class="flexpay_flexpaycard_container__GnRx9"]
${View_Sim}             //a[@data-di-id="di-id-f6103190-3a42ff4a"]
${Deals}                //div[10]//div[2]//div[1]//div[1]//span[1]   #(.//*[@class="simo-card-ee_text_container__30ltg"]/div[@class="simo-card-ee_plan_details__1G4nS mt-4"]/div[@class="simo-card-ee_plan_details_wrapper__2oiEq relative pr-4 mb-5"]/span[@class="simo-card-ee_was_data__37BKi"])[7]
#(.//*[@class="simo-card-ee_was_data__37BKi"])[7]